### PR TITLE
Revert "two files added"

### PR DESCRIPTION
**Pull request by aartiwanjale**
Reverts SSPatil4/ThirdRepository#1

### CODE REVIEW

**Comment by git4saurabh** [comment]
chup baith na

**Comment by aartiwanjale** [comment]
This Program is not good

**Comment by git4saurabh** [comment]
you aren's able to understant this pro

**Comment by aartiwanjale** [comment]
ok no issue bye

**Comment by git4saurabh** [comment]
> ok no issue bye

it's okay I knew

**Pull request merged**
